[mod_rddtool]: fix warnings
In function mod_rrd_free, the status variable is removed since the
process status is ignored.

	mod_rrdtool.c: In function ‘mod_rrd_free’:
	mod_rrdtool.c:82:7: error: unused variable ‘status’ [-Werror=unused-variable]
	   int status;
	       ^~~~~~

In function mod_rrd_create_pipe, the srv and p paramaters are unused.

	mod_rrdtool.c: In function ‘mod_rrd_create_pipe’:
	mod_rrdtool.c:96:40: error: unused parameter ‘srv’ [-Werror=unused-parameter]
	 static int mod_rrd_create_pipe(server *srv, plugin_data *p) {
	                                        ^~~
	mod_rrdtool.c:96:58: error: unused parameter ‘p’ [-Werror=unused-parameter]
	 static int mod_rrd_create_pipe(server *srv, plugin_data *p) {
	                                                          ^