[core] fix build issue without ipv6 support
This patch fixes the build issue introduced with when code has been
shared in commit a448886485ea89efed2996838be6ac42b4dd81a9.

	http-header-glue.c: In function 'http_cgi_headers':
	http-header-glue.c:1555:39: error: 'b2' undeclared (first use in this function)
	http-header-glue.c:1555:39: note: each undeclared identifier is reported only once for each function it appears in

github: closes #79