[mod_webdav] no COPYFILE_CLONE_FORCE on OSX <10.12 (fixes #3142)
(thx ryandesign)

There is no COPYFILE_CLONE_FORCE on OSX <10.12  so fall back to using
fcopyfile() to avoid race condition on source (if changed to dir) if
using copyfile() with flags equivalent to COPYFILE_CLONE_FORCE, but
without the 'force' flag.

x-ref:
  "error: use of undeclared identifier 'COPYFILE_CLONE_FORCE'"
  https://redmine.lighttpd.net/issues/3142