[core]: fix warnings
In function server_main, the num_childs variable is unused if HAVE_FORK
is not set.

	server.c: In function ‘server_main’:
	server.c:840:6: error: unused variable ‘num_childs’ [-Werror=unused-variable]
	  int num_childs = 0;
	      ^~~~~~~~~~

In function stat_cache_init, the srv paramater is unused.

	stat_cache.c: In function ‘stat_cache_init’:
	stat_cache.c:112:37: warning: unused parameter ‘srv’ [-Wunused-parameter]
	 stat_cache *stat_cache_init(server *srv) {
	                                     ^~~

Wrap stat_cache_handle_fdevent function definition with #ifdef
HAVE_FAM... #endif.

This drops the following warning.

	stat_cache.c: At top level:
	stat_cache.c:110:18: warning: ‘stat_cache_handle_fdevent’ declared ‘static’ but never defined [-Wunused-function]
	 static handler_t stat_cache_handle_fdevent(server *srv, void *_fce, int revent);
	                  ^~~~~~~~~~~~~~~~~~~~~~~~~