[ci] #undef _XOPEN_SOURCE on Solaris
fixes compile error when #define _XOPEN_SOURCE 700 is used, e.g. error
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.5.0/include-fixed/sys/feature_tests.h:346:2:
error: #error "Compiler or options invalid for pre-UNIX 03 X/Open applications and pre-2001 POSIX applications"

Alternative changes (TBD) might be needed on Solaris derivatives,
e.g. OpenSolaris or Illumos